channels:
  - conda-forge

dependencies:
  - pip=22.3.1
  - python=3.10.8
  - lxml=4.9.1
  - numpy=1.23.3
  - pandas=1.3.5
  - pythia8=8.307
  - sphinx=5.3.0
  - sphinx-autoapi=2.0.0
  - pygit2=1.10.1
  - rich=12.6.0
  - pip:
    - sphinx_mdinclude==0.5.3
    - sphinx-immaterial==0.10.0
