name: Publish conda

on:
  push

jobs:
  publish:
    - name: Build Conda Packages
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda install conda-build anaconda-client conda-verify
        conda config --set anaconda_upload yes
        conda build --token "${ANACONDA_TOKEN}" .conda/
